# Note: You have to define SSH_PRIVATE_KEY, SSH_PORT and SSH_HOSTDEST with gitlab variables.
variables:
  PROD_S3_BUCKET_NAME: "www.finleap.tech"
  STAGE_S3_BUCKET_NAME: "staging.finleap.tech"
  PROD_BLOG_URL: "https://www.finleap.tech"
  STAGING_BLOG_URL: "https://staging.finleap.tech"
stages:
  - stage_build
  - build
  - stage
  - deploy
build:
  stage: build
  image: jguyomard/hugo-builder:latest
  script:
  - git submodule update --init --recursive
  - hugo -d public_html -b "${PROD_BLOG_URL}"
  cache:
    paths:
    - public_html
  artifacts:
    paths:
    - public_html
  only:
  - master

stage_build:
  stage: stage_build
  image: jguyomard/hugo-builder:latest
  script:
  - git submodule update --init --recursive
  - hugo -d staging_html -b "${STAGING_BLOG_URL}"
  cache:
    paths:
    - staging_html
  artifacts:
    paths:
    - staging_html
  except:
  - master

deploy:
  stage: deploy
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./public_html s3://$PROD_S3_BUCKET_NAME/ --recursive --acl public-read
  only:
  - master

stage:
  stage: stage
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./staging_html s3://$STAGE_S3_BUCKET_NAME/ --recursive --acl public-read
  except:
  - master
