# Note: You have to define SSH_PRIVATE_KEY, SSH_PORT and SSH_HOSTDEST with gitlab variables.
variables:
  AWS_ACCESS_KEY_ID: "AKIA3WVT42PPBWCXOTV3"
  AWS_SECRET_ACCESS_KEY: "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”
stages:
  - build
  - deploy
build:
  stage: build
  image: jguyomard/hugo-builder:latest
  script:
  - git submodule update --init --recursive
  - hugo -d public_html -b "${BLOG_URL}"
  cache:
    paths:
    - public_html
  artifacts:
    paths:
    - public_html
  only:
  - master
deploy:
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./ s3://www.finleap.tech.s3-website.eu-central-1.amazonaws.com/ --recursive --exclude "*" --include "*.html"
  only:
  - master
