# Note: You have to define SSH_PRIVATE_KEY, SSH_PORT and SSH_HOSTDEST with gitlab variables.
variables:
  S3_BUCKET_NAME: "www.finleap.tech"
stages:
  - build
  - deploy
build:
  stage: build
  image: jguyomard/hugo-builder:latest
  script:
  - git submodule update --init --recursive
  - hugo -d public_html -b "${BLOG_URL}"
  cache:
    paths:
    - public_html
  artifacts:
    paths:
    - public_html
  only:
  - master
deploy:
  stage: deploy
  image: python:latest
  script:
  - pip install awscli
  - aws s3 cp ./ s3://$S3_BUCKET_NAME/ --recursive --exclude "*" --include "*.html"
  only:
  - master
