languageCode = "en-us"
defaultContentLanguage = "en"
title = "finleap engineering blog"
subtitle = "our blog"
theme = "hyde"

relativeurls = true
baseurl = "https://engineering.finleap.com/"

# Enable syntax highlighting.

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

# Your Google analytics code.
googleAnalytics = "UA-158807388-1"

[params]
	description = "interesting things that the finleap engineering teams have been doing"
	themeColor = "theme-base-0d"

	[Menus]
    footer = [
      {Name = "www.finleap.com", URL = "https://www.finleap.com", weight = 500},
    ]
	