languageCode = "en-us"
defaultContentLanguage = "en"
title = "Tech Blog"
theme = "hyde"

#relativeurls = true
#uglyurls = true
baseurl = "https://finleap.tech/"

# Enable syntax highlighting.

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

# Your Google analytics code.
# googleAnalytics = "UA-123-45"
# Your Disqus sortname.
# disqusShortname = "localhost"

[params]
	# Blog subtitle which appears below blog title. Supports markdown.
	# subtitle = "Interesting things that the Finleap tech team have been doing"
	# # Number of posts to show in recent posts list (Optional). Defaults to 10.
	# recentPostsCount = 10
	# # Content types which are excluded from recent posts and archive page (Optional). Defaults to ["page"]
	# excludedTypes = ["page"]
	# # Content types which are excludes Disqus comments (Optional). Defaults to ["page"]
	# disableDisqusTypes = ["page"]
	# # If social media links are enabled then enable this to fetch icons from CDN instead of hosted on your site.
	# featherIconsCDN = true

	description = "Interesting things that the Finleap tech team have been doing"
	themeColor = "theme-base-0d"

	[Menus]
	  main = [
	    	{Name = "Github", URL = "https://github.com/finleap", weight = 200},
			{Name = "We're hiring!", URL = "https://www.finleap.com/careers/jobs/", weight = 100},
			{Name = "Twitter", URL = "https://twitter.com/finleap", weight = 300},
	    	{Name = "finleap.com", URL = "https://www.finleap.com", weight = 400}
	  ]

# # Main menu which appears below site header.
# [[menu.main]]
# name = "Home"
# url = "/"
# weight = 1
#
# [[menu.main]]
# name = "All posts"
# url = "/posts"
# weight = 2
#
# [[menu.main]]
# name = "About"
# url = "/about"
# weight = 3
#
# [[menu.main]]
# name = "Tags"
# url = "/tags"
# weight = 4

# Social media links which shows up on site header.
# Uses feather icons for icons. You can [search icon names from here](https://feathericons.com/).
# [[params.social]]
# name = "Github"
# icon = "github"
# url = "https://github.com/finleap"
#
# [[params.social]]
# name = "Twitter"
# icon = "twitter"
# url = "https://twitter.com/finleap"
#
# [[params.social]]
# name = "Instagram"
# icon = "instagram"
# url = "https://www.instagram.com/finleap_gmbh"

# Enable tags.
# [taxonomies]
#   tag = "tags"
