languageCode = "en-us"
defaultContentLanguage = "en"
title = "Finleap Engineering Blog"
theme = "hyde"

relativeurls = true
baseurl = "https://engineering.finleap.com/"

# Enable syntax highlighting.

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

# Your Google analytics code.
googleAnalytics = "UA-158807388-1"

[params]
	description = "Interesting things that the Finleap engineering teams have been doing"
	themeColor = "theme-base-0d"

	[Menus]
	  main = [
	    {Name = "Github", URL = "https://github.com/finleap", weight = 200},
			{Name = "We're hiring!", URL = "https://www.finleap.com/careers/jobs/", weight = 100},
			{Name = "Twitter", URL = "https://twitter.com/finleap", weight = 300},
	    {Name = "finleap.com", URL = "https://www.finleap.com", weight = 400}
	  ]
	