name = "Finleap"
license = "CC BY 4.0"
licenselink = "https://creativecommons.org/licenses/by/4.0/"
description = "The Finleap theme is ported from Cayman."
min_version = "0.54.0"

[author]
  name = "Tim Duckett"

[original]
  name = "Finleap"
