name: Live Hugo build & deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
      # with:
      #   submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        # extended: true

    - name: Build
      env:
        PROD_BLOG_URL: ${{ secrets.PROD_BLOG_URL }}
      run: hugo --minify --destination public_html --baseURL "$PROD_BLOG_URL"

    - name: Upload S3 Contents
      run: |
        aws s3 sync ./public_html s3://$PROD_AWS_S3_BUCKET --acl public-read --cache-control "public, must-revalidate, proxy-revalidate, max-age=2678400, s-maxage=2678400"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PROD_AWS_S3_BUCKET: ${{ secrets.PROD_AWS_S3_BUCKET }}

    - name: Invalidate finleap.tech Cloudfront distribution
      run: |
        aws cloudfront create-invalidation --distribution-id $PROD_AWS_CLOUDFRONT_DIST --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PROD_AWS_CLOUDFRONT_DIST: ${{ secrets.PROD_AWS_CLOUDFRONT_DIST }}

    - name: Invalidate engineering.finleap Cloudfront distribution
      run: |
        aws cloudfront create-invalidation --distribution-id $PROD_MAIN_AWS_CLOUDFRONT_DIST --paths "/*"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        PROD_MAIN_AWS_CLOUDFRONT_DIST: ${{ secrets.PROD_MAIN_AWS_CLOUDFRONT_DIST }}